name: GitHub Actions Build and Deploy

on:
  # 手动运行工作流程（workflow_dispatch 事件触发器配置后可以在actions下手动运行工作流）
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 指定服务器的运行环境：最新版本ubuntu
    steps:
      # 使用 actions/checkout@v4 拉取代码到 ubuntu 上
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 设置 node 的版本并安装 npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 构建项目
      - name: Build
        run: npm run build
      # 部署到 GitHub Pages
      - name: Deploy
        run: |
          # Clean old worktrees
          git worktree list
          git worktree remove <path_to_worktree> --force || true  # 可以忽略移除失败

        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          # 指定仓库：你要发布的仓库路径名
          repository-name: shaoshaui/react18-vite-ts-reactrouter6-antd5
          # 部署到 deploy-pages 分支，也就是部署后提交到那个分支
          branch: gh-pages
          # 填写打包好的目录名称路径，本项目配置在根目录
          folder: dist
